# FAPS Knowledge Assistant Configuration

# Application Settings
app:
  name: "FAPS Knowledge Assistant"
  language: "de"
  timezone: "Europe/Berlin"
  debug: false

# UI Configuration
ui:
  page_title: "FAPS Knowledge Assistant"
  page_icon: "🔍"
  logo_path: "faps_logo.png"
  main_title: "FAPS Knowledge Assistant"
  description: "Intelligenter Assistent für FAPS-Ressourcen mit natürlicher Sprachverarbeitung"
  subtitle: "Durchsuchen Sie NAS-Dateien, Wiki-Inhalte und Webressourcen mit einfachen Fragen auf Deutsch"

# Service Endpoints
services:
  ollama:
    host: "http://ollama:11434"
    model: "qwen2.5:20b"
    timeout: 30
  
  lancedb:
    uri: "http://lancedb:8080"
    table_name: "faps_documents"
  
  streamlit:
    port: 8501
    host: "0.0.0.0"

# Data Sources
data_sources:
  nas:
    mount_path: "/mnt/nas"
    enabled: true
    read_only: true
    supported_extensions: [".pdf", ".doc", ".docx", ".txt", ".xlsx", ".xls", ".ppt", ".pptx", ".md", ".rtf", ".odt", ".ods", ".odp", ".csv"]
  
  wiki:
    url: "https://wiki.faps.uni-erlangen.de/"
    enabled: true
    requires_auth: true
    auth_type: "basic"
  
  fau_internal:
    url: "https://www.intern.fau.de/"
    enabled: true
    requires_auth: false
  
  idm_fau:
    url: "https://www.idm.fau.de/"
    enabled: true
    requires_auth: true
    auth_type: "sso"
    sso_url: "https://sso.uni-erlangen.de"

# Search Configuration
search:
  max_results: 10
  default_sources: ["nas", "wiki", "fau_internal"]
  chunk_size: 1000
  overlap: 200
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

# Security Settings
security:
  session_timeout: 3600  # seconds
  max_sessions: 5
  require_https: false
  allowed_origins: ["*"]

# Performance Settings
performance:
  rate_limit_delay: 1.0  # seconds between requests
  max_concurrent_requests: 5
  cache_ttl: 3600  # seconds
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "faps_assistant.log"

# German Language Responses
responses:
  fallback: "Entschuldigung, ich konnte keine spezifischen Informationen zu Ihrer Anfrage finden."
  connection_error: "Verbindungsfehler zu den Datenquellen."
  auth_required: "Authentifizierung erforderlich für diese Ressource."
  processing: "Ich durchsuche die FAPS-Ressourcen..."
  
messages:
  welcome: "Hallo! Ich bin Ihr FAPS Knowledge Assistant. Fragen Sie mich nach Informationen aus dem NAS, Wiki oder anderen FAPS-Ressourcen. Wie kann ich Ihnen helfen?"
  auth_success: "Authentifizierung erfolgreich!"
  auth_failed: "Authentifizierung fehlgeschlagen."
  index_updated: "Index erfolgreich aktualisiert!"
  cache_cleared: "Cache geleert!"